---
hide_body: false
fields:
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default:
  - category
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default:
  - tag1
  - tag2
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- name: author
  label: Author
  type: text
  hidden: false
  default: ''
